### ISSUE TITLE
'grep' is not recognized Windows 11

### ISSUE THREAD

**Issue by rbxrootx** [SimonMo88/ghost-static-site-generator#76]
Error: Command failed: wget --help | grep "show-progress" || true
'grep' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at shouldShowProgress (C:\Users\Eli\AppData\Roaming\npm\node_modules\ghost-static-site-generator\src\constants\OPTIONS.js:20:32)
    at Object.<anonymous> (C:\Users\Eli\AppData\Roaming\npm\node_modules\ghost-static-site-generator\src\constants\OPTIONS.js:44:22)

**Comment by djekanovic** [comment]
Same

**Comment by djekanovic** [comment]
Use this choco install -y grep

**Comment by SimonMo88** [comment]
Docs for windows are now available [here](https://github.com/SimonMo88/ghost-static-site-generator?tab=readme-ov-file#windows)
